site_name: Melonland

pages:
- Home: index.md
- HD Quick Start:
    - Overview: quickstart.md
    - Install Webdriver: install-webdriver.md
- HD Features:
    - Preamble Options: features/preamble.md
    - Finding Elements: features/finding-elements.md
- Contributing: contributing/contributing.md

site_dir: dist/docs

theme: readable