site_name: Melonland

pages:
- Home: index.md
- HD Guide:
    - Quick Start: guide/quickstart.md
    - Example Snippets: guide/snippets.md
- HD Reference:
    - Preamble Options: reference/preamble.md
    - Finding Elements: reference/finding-elements.md
    - Backend API: reference/api.md
- HD FAQ:
    - FAQ: faq.md
    - Install Webdriver: faq/install-webdriver.md
    - Contributing: faq/contributing.md
    - Regex: faq/regex.md

site_dir: dist/docs

theme: readable
theme: mkdocs

markdown_extensions:
    - toc:
        permalink: 

# CSS files and JS files are automatically included, in particular
# docs.css and docs.js.