site_name: Honeydew

pages:
- Home: index.md
- Quick Start:
    - Overview: 'quickstart.md'
    - Install Webdriver: 'install-webdriver.md'
- Features:
    - 'Preamble Options': 'features/preamble.md'
    - 'Finding Elements': 'features/finding-elements.md'

site_dir: dist/docs

theme: readable